language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx solstice
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: tyMgAqrjac4Mrebqj6zl/x1gfIRDnVLTobcyfZBeVHqFaY2J2HJCz7iUFMn1EFfzQl0oAkN8qijj/U2ZkrM9AEdguvwyJIXqogmuiTcpg8CT+shv8B7i2I47xcpZk1BoNJaOjP2PPX9zeV+dVOJl4CJcK33ixyB3OMx8iW1f1qp6BGFbZRzuWJlZ/Klb9xcY/Gu2pQ3VYkZtR98JXYkCA/PX4DkNvrGnkwZ/EF1s6Tm5CC6qRx0yVDX8hgFHoVjaPnZHmHscc70HawMUI/csYG1pjpKjaWBWA0NJDsuzgs1IizPTuwKBvsJDMdcQD74/KczHQr9c8/RaWyF/NV+KgESSYRUwmIRAJO58ZZQ3ZTckRVTqK67x6soyYQ5Ve+YQy6n5Ow/z7f/BMmXXUTWMMdYoCqFQJKbP9sU5UKB70jo0QMemM7SEwV4P2Ah4q7IqfIERTa+rnz0MUdxQ/BIxe+Le5LiejExYOFfQBvLoSeaLQyjdNBpah45rv6qF1Av9EPbVvJUWuPO9dd1QnN6sh+oj+sx/u2cH1Vi+iqcGdwQPQmMs3Z8UBRRchf+EKyDbh6v6dPuRRGK79QmFHfWjraMFPzlVp/zBQ4lV58+L7q2D2Fmm3tq2YBrHkhWqWMCAQpYBL13Q19fojBeUfWyYW2HlPfGtdbAjJdOdO3vsntY=
    on:
      branch: master
      tags: true